apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pacman-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pacman
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 1
